### PR TITLE
Fix Camera Jerking, Add Support for Saving/Loading Paths, and Make Double-Digit Path Node Indices Easier To Read

### PR DESCRIPTION
**Pull request by misson20000**
Details are in commit messages for the most part. The file format for path nodes is a simple JSON format, just a list of Position objects serialized via Gson.
Being able to save/load camera paths is cool, because I've been trying to make a video where I can record something, then change it, record it again on the same path, and use a video editor to sync up the recordings and change the opacity of one of the layers. It's a little easier if I don't have to worry about my game crashing and losing the camera path.

Oh, and you'll probably want to increment the version number.

### CODE REVIEW

**Comment by misson20000** [comment]
Uh oh, my camera jerking "fix" might've actually broke something. I think it's related to passing through blocks in spectator mode.

**Comment by misson20000** [comment]
I see. Entity.setPositionAndRotation fights to keep prevRotationYaw within [-180,180), but keeps rotationYaw within [0, 360) which makes the camera spaz out at certain angles. Guess a little jittering isn't what `//this fixes camera jerking` was meant to fix, and that passing through blocks had nothing to do with it at all.

**Comment by CrushedPixel** [comment]
Actually, the camera jerking bug is caused by the server teleporting you back to where you were before starting to travel the camera path, as the move packets sent are over a too large distance (the server considers this cheating and rejects your position). A possible fix would be to move the player to the first camera point over multiple teleports.

**Comment by misson20000** [comment]
I think we're talking about different jerking bugs. The one I fixed originally looked like the camera was vibrating a little. I could make a video tomorrow. The fix I removed in that commit and later reinstated prevented the camera from switching back and forth between two orientations very quickly. Is the camera jerking bug you're mentioning a rubber banding-type issue,  maybe #1? I haven't seen any of that, and commit 4eaeaf2 fixed all the problems I was having.

**Pull request merged**
